# Generated by Django 5.1.6 on 2025-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayesian_network', models.CharField(max_length=255, verbose_name='Bayesian network')),
            ],
        ),
    ]
