# Generated by Django 5.1.6 on 2025-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayesian_networks', '0003_rename_challenge_bayesiannetwork_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayesiannetwork',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
